jdk: oraclejdk8
env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - ANDROID_VERSION=28 # Android 9 (API level 28)
  - BUILD_TOOLS_VERSION=29.0.0
  - NODEJS=10
  - CORDOVA_CLI=latest # latest cordova version
matrix:
  include:
  - os: linux
    sudo: false
    language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-$BUILD_TOOLS_VERSION
      - android-$ANDROID_VERSION
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt:
        chrome: stable
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
        - jq
        - gradle
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
  - os: osx
    sudo: false
    language: objective-c
	osx_image: xcode9.4
before_install:
  - nvm install $NODEJS
  - npm install -g cordova@$CORDOVA_CLI
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-android.sh ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build-osx.sh ; fi
before_deploy:
  - export DATE=$(date +'DATE_%Y_%m_%d_%H%M%S')
  - export GIT_COMMIT=COMMIT_$(git log --format=%h -1)
  - export APP_NAME=$(cat www/config.xml | grep \<name\> | cut -d '>' -f2 | cut -d '<' -f1)
  - export APP_VERSION_CURRENT=$(cat www/config.xml | grep widget | grep id | grep version | cut -d '"' -f4)
  - export APK_NAME=${APP_NAME}-${APP_VERSION_CURRENT}-${DATE}-${GIT_COMMIT}
  - export APK_NAME=${APK_NAME// /}
  - export TRAVIS_TAG=${TRAVIS_TAG:-${APK_NAME}}
  - git tag ${TRAVIS_TAG// /}
  - git tag -l
  - cp $TRAVIS_BUILD_DIR/app-release.apk $TRAVIS_BUILD_DIR/${APK_NAME// /}.apk
deploy:
  provider: releases
  api_key:
    secure: $YOUR_API_KEY_ENCRYPTED
  file:
    - "$TRAVIS_BUILD_DIR/${APK_NAME// /}.apk"
    - "$TRAVIS_BUILD_DIR/keys.zip"
  skip_cleanup: true
  on:
    all_branches: true
